import React from 'react';
import {createRoot} from 'react-dom/client';
import './src/style.css';
import {OnboardingProvider} from './src/context/OnboardingContext';
import Modal from './src/components/common/Modal';
import A from './src/components/onboarding/StepBasicInfo';
import B from './src/components/onboarding/StepFitnessLevel';
import C from './src/components/onboarding/StepGoals';
import D from './src/components/onboarding/StepAvailability';
import E from './src/components/onboarding/StepHealth';
import F from './src/components/onboarding/StepReview';
const step=Number(new URLSearchParams(location.search).get('step')||1);
const Step=[A,B,C,D,E,F][step-1];
createRoot(document.getElementById('root')).render(<OnboardingProvider><Modal overlayClassName="onboarding-modal-backdrop" className="onboarding-modal-content" hideCloseButton><div className="onboarding-modal-header"><div className="onboarding-header-top"><strong>LOWROX</strong><span>{step} / 6</span></div><div className="onboarding-progress-bar"/></div><div className="onboarding-step-region"><Step onNext={()=>{}} onPrev={()=>{}} onSubmit={()=>{}} /></div></Modal></OnboardingProvider>);
